CREATE TABLE `kb_image_sets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`asin` varchar(20) NOT NULL,
	`productTitle` varchar(512),
	`category` varchar(128),
	`brand` varchar(128),
	`overallAnalysis` text,
	`userEditedOverallAnalysis` text,
	`overallScore` int,
	`status` enum('crawling','analyzing','pending_review','confirmed','archived') NOT NULL DEFAULT 'crawling',
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_image_sets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_images` (
	`id` int AUTO_INCREMENT NOT NULL,
	`imageSetId` int NOT NULL,
	`imageUrl` varchar(1024) NOT NULL,
	`imagePosition` enum('main','secondary','aplus') NOT NULL,
	`positionIndex` int,
	`tagCategory` varchar(64),
	`tagColorScheme` varchar(64),
	`tagImageType` varchar(64),
	`tagDesignStyle` varchar(64),
	`aiDimensionAnalysis` text,
	`userEditedDimensionAnalysis` text,
	`singleImageScore` int,
	`highlights` text,
	`tagsConfirmed` int NOT NULL DEFAULT 0,
	`analysisConfirmed` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_images_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_listing_copywriting` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`asin` varchar(20) NOT NULL,
	`productTitle` varchar(512),
	`category` varchar(128),
	`brand` varchar(128),
	`titleText` text,
	`bulletPoints` text,
	`longDescription` text,
	`aPlusContent` text,
	`qaContent` text,
	`crawledData` text,
	`aiAnalysis` text,
	`userEditedAnalysis` text,
	`tags` text,
	`overallScore` int,
	`status` enum('crawling','analyzing','pending_review','confirmed','archived') NOT NULL DEFAULT 'crawling',
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_listing_copywriting_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_operation_skills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`sourceType` enum('upload_pdf','upload_word','upload_excel','upload_ppt','upload_md','upload_image','upload_mindmap','url','manual') NOT NULL,
	`sourceUrl` varchar(1024),
	`fileUrl` varchar(1024),
	`originalFileName` varchar(256),
	`extractedContent` text,
	`aiSummary` text,
	`userEditedSummary` text,
	`categories` text,
	`tags` text,
	`practicalityScore` int,
	`status` enum('parsing','analyzing','pending_review','confirmed','archived') NOT NULL DEFAULT 'parsing',
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_operation_skills_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_product_innovations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`asin` varchar(20) NOT NULL,
	`productUrl` varchar(1024),
	`productTitle` varchar(512),
	`brand` varchar(128),
	`price` varchar(50),
	`bsr` int,
	`rating` varchar(10),
	`reviewCount` varchar(20),
	`category` varchar(128),
	`bulletPoints` text,
	`imageUrls` text,
	`crawledData` text,
	`aiAnalysis` text,
	`userEditedAnalysis` text,
	`tags` text,
	`overallScore` int,
	`status` enum('crawling','analyzing','pending_review','confirmed','archived') NOT NULL DEFAULT 'crawling',
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_product_innovations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kb_videos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`asin` varchar(20),
	`videoUrl` varchar(1024) NOT NULL,
	`videoTitle` varchar(512),
	`category` varchar(128),
	`duration` int,
	`thumbnailUrl` varchar(1024),
	`transcriptText` text,
	`keyframeUrls` text,
	`aiAnalysis` text,
	`userEditedAnalysis` text,
	`tags` text,
	`overallScore` int,
	`status` enum('downloading','transcribing','analyzing','pending_review','confirmed','archived') NOT NULL DEFAULT 'downloading',
	`confirmedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kb_videos_id` PRIMARY KEY(`id`)
);
