CREATE TABLE `image_workflow_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`currentStep` int NOT NULL DEFAULT 1,
	`step1AiResult` text,
	`step1UserEdit` text,
	`step1Confirmed` int NOT NULL DEFAULT 0,
	`step2AiResult` text,
	`step2UserEdit` text,
	`step2Confirmed` int NOT NULL DEFAULT 0,
	`step3AiResult` text,
	`step3UserEdit` text,
	`step3Confirmed` int NOT NULL DEFAULT 0,
	`step4AiResult` text,
	`step4UserEdit` text,
	`step4Confirmed` int NOT NULL DEFAULT 0,
	`step5AiResult` text,
	`step5AiResultCn` text,
	`step5UserEdit` text,
	`step5Confirmed` int NOT NULL DEFAULT 0,
	`pdfUrl` text,
	`status` enum('in_progress','completed') NOT NULL DEFAULT 'in_progress',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `image_workflow_sessions_id` PRIMARY KEY(`id`)
);
