CREATE TABLE `execution_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`product_profile_id` int NOT NULL,
	`user_id` int NOT NULL,
	`plan_id` int,
	`period` varchar(50) NOT NULL,
	`period_type` enum('weekly','monthly','quarterly') NOT NULL DEFAULT 'monthly',
	`baseline_sales` decimal(12,2),
	`baseline_profit` decimal(12,2),
	`baseline_profit_rate` decimal(5,2),
	`baseline_order_conv_rate` decimal(5,2),
	`baseline_search_conv_rate` decimal(5,2),
	`baseline_ad_conv_rate` decimal(5,2),
	`baseline_ranking` int,
	`baseline_rating` decimal(3,2),
	`actual_sales` decimal(12,2),
	`actual_profit` decimal(12,2),
	`actual_profit_rate` decimal(5,2),
	`actual_order_conv_rate` decimal(5,2),
	`actual_search_conv_rate` decimal(5,2),
	`actual_ad_conv_rate` decimal(5,2),
	`actual_ranking` int,
	`actual_rating` decimal(3,2),
	`target_sales` decimal(12,2),
	`target_profit` decimal(12,2),
	`target_order_conv_rate` decimal(5,2),
	`target_search_conv_rate` decimal(5,2),
	`target_ad_conv_rate` decimal(5,2),
	`achievement_summary` text,
	`key_actions` text,
	`lessons_learned` text,
	`next_period_plan` text,
	`strategist_feedback` text,
	`strategist_rating` enum('S','A','B','C','D'),
	`ai_analysis` text,
	`ai_analysis_locked` int DEFAULT 0,
	`review_status` enum('draft','submitted','reviewed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `execution_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `team_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`product_profile_id` int NOT NULL,
	`user_id` int NOT NULL,
	`title` varchar(200) NOT NULL,
	`description` text,
	`task_status` enum('backlog','todo','in_progress','review','done') NOT NULL DEFAULT 'todo',
	`task_priority_team` enum('urgent','high','medium','low') NOT NULL DEFAULT 'medium',
	`category` varchar(100),
	`assignee_id` int,
	`assignee_name` varchar(100),
	`start_date` varchar(20),
	`due_date` varchar(20),
	`completed_at` timestamp,
	`estimated_hours` decimal(5,1),
	`actual_hours` decimal(5,1),
	`linked_todo_id` int,
	`linked_plan_action_id` int,
	`tags` text,
	`sort_order` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `team_tasks_id` PRIMARY KEY(`id`)
);
