CREATE TABLE `batch_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batch_id` int NOT NULL,
	`user_id` varchar(255),
	`user_name` varchar(255),
	`action` varchar(100) NOT NULL,
	`from_step` int,
	`to_step` int,
	`details` text,
	`created_at` bigint NOT NULL,
	CONSTRAINT `batch_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batch_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batch_id` int NOT NULL,
	`sku` varchar(255) NOT NULL,
	`asin` varchar(50),
	`product_name` varchar(500),
	`quantity` int NOT NULL DEFAULT 0,
	`unit_cost` decimal(10,2) DEFAULT '0',
	`total_cost` decimal(12,2) DEFAULT '0',
	`weight` decimal(8,2),
	`volume` decimal(10,4),
	`fnsku` varchar(50),
	`lingxing_product_id` varchar(255),
	`created_at` bigint NOT NULL,
	CONSTRAINT `batch_products_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `batch_step_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`batch_id` int NOT NULL,
	`step_number` int NOT NULL,
	`step_name` varchar(100) NOT NULL,
	`expected_days` int NOT NULL DEFAULT 0,
	`actual_start_at` bigint,
	`actual_end_at` bigint,
	`actual_days` int,
	`notes` text,
	`step_status` enum('pending','active','completed','skipped') NOT NULL DEFAULT 'pending',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `batch_step_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `replenishment_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`sku` varchar(255) NOT NULL,
	`asin` varchar(50),
	`store_name` varchar(255),
	`current_available_inventory` int NOT NULL DEFAULT 0,
	`daily_sales_avg` decimal(10,2) DEFAULT '0',
	`days_of_stock_remaining` int NOT NULL DEFAULT 0,
	`full_cycle_days` int NOT NULL DEFAULT 0,
	`recommended_quantity` int NOT NULL DEFAULT 0,
	`recommended_order_date` bigint,
	`recommended_shipping_method` varchar(100),
	`estimated_arrival_date` bigint,
	`confidence` decimal(3,2) DEFAULT '0',
	`ai_suggestion` json,
	`risk_factors` json,
	`alternative_plans` json,
	`alert_level` varchar(20),
	`alert_sent_at` bigint,
	`user_confirmed` int NOT NULL DEFAULT 0,
	`predicted_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `replenishment_predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shipping_batches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`batch_name` varchar(500) NOT NULL,
	`batch_number` int NOT NULL,
	`store_name` varchar(255),
	`source_warehouse` varchar(255),
	`transit_warehouse` varchar(255),
	`destination_warehouse` varchar(255),
	`shipping_method` varchar(100),
	`current_step` int NOT NULL DEFAULT 1,
	`batch_status` enum('active','completed','cancelled','paused') NOT NULL DEFAULT 'active',
	`tracking_number` varchar(255),
	`vehicle_plate` varchar(100),
	`carrier_name` varchar(255),
	`international_tracking_number` varchar(255),
	`international_carrier` varchar(255),
	`planned_quantity` int NOT NULL DEFAULT 0,
	`ordered_quantity` int NOT NULL DEFAULT 0,
	`shipped_quantity` int NOT NULL DEFAULT 0,
	`warehouse_received_quantity` int NOT NULL DEFAULT 0,
	`international_shipped_quantity` int NOT NULL DEFAULT 0,
	`amazon_received_quantity` int NOT NULL DEFAULT 0,
	`amazon_stocked_quantity` int NOT NULL DEFAULT 0,
	`amazon_total_inventory` int NOT NULL DEFAULT 0,
	`amazon_available_inventory` int NOT NULL DEFAULT 0,
	`amazon_reserved_inventory` int NOT NULL DEFAULT 0,
	`amazon_inbound_inventory` int NOT NULL DEFAULT 0,
	`amazon_unfulfillable_inventory` int NOT NULL DEFAULT 0,
	`currency` varchar(10) NOT NULL DEFAULT 'USD',
	`total_product_cost` decimal(12,2) DEFAULT '0',
	`total_shipping_cost` decimal(12,2) DEFAULT '0',
	`total_other_cost` decimal(12,2) DEFAULT '0',
	`amazon_commission_rate` decimal(5,2),
	`batch_owner` varchar(255),
	`logistics_owner` varchar(255),
	`lingxing_delivery_order_id` varchar(255),
	`lingxing_purchase_order_id` varchar(255),
	`lingxing_purchase_plan_id` varchar(255),
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `shipping_batches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `step_time_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`batch_id` int NOT NULL,
	`step_number` int NOT NULL,
	`shipping_method` varchar(100),
	`carrier_name` varchar(255),
	`route` varchar(255),
	`expected_days` int,
	`actual_days` int,
	`month_of_year` int,
	`created_at` bigint NOT NULL,
	CONSTRAINT `step_time_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `step_time_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`template_name` varchar(200) NOT NULL,
	`shipping_method` varchar(100) NOT NULL,
	`step1_days` int NOT NULL DEFAULT 3,
	`step2_days` int NOT NULL DEFAULT 14,
	`step3_days` int NOT NULL DEFAULT 3,
	`step4_days` int NOT NULL DEFAULT 1,
	`step5_days` int NOT NULL DEFAULT 3,
	`step6_days` int NOT NULL DEFAULT 2,
	`step7_days` int NOT NULL DEFAULT 30,
	`step8_days` int NOT NULL DEFAULT 7,
	`step9_days` int NOT NULL DEFAULT 3,
	`is_default` int NOT NULL DEFAULT 0,
	`ai_suggested` int NOT NULL DEFAULT 0,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `step_time_templates_id` PRIMARY KEY(`id`)
);
