CREATE TABLE `competitor_ad_benchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plan_id` int NOT NULL,
	`competitor_brand` varchar(200) NOT NULL,
	`competitor_asin` varchar(20),
	`ad_type` enum('sp','sb','sd','dsp','mixed') NOT NULL DEFAULT 'mixed',
	`acos` decimal(8,2),
	`ctr` decimal(8,4),
	`cvr` decimal(8,4),
	`cpc` decimal(8,2),
	`cpa` decimal(8,2),
	`total_spend` decimal(12,2),
	`total_sales` decimal(12,2),
	`total_orders` int,
	`total_impressions` int,
	`total_clicks` int,
	`data_period` varchar(50),
	`analysis_notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitor_ad_benchmarks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promotion_phases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plan_id` int NOT NULL,
	`phase_name` varchar(200) NOT NULL,
	`phase_type` enum('launch','growth','maturity','optimization','clearance','custom') NOT NULL DEFAULT 'custom',
	`bsr_range_start` int,
	`bsr_range_end` int,
	`duration_days` int,
	`start_date` varchar(10),
	`end_date` varchar(10),
	`ad_budget_daily` decimal(10,2),
	`target_acos` decimal(8,2),
	`key_strategy` text,
	`milestones` text,
	`status` enum('pending','active','completed','skipped') NOT NULL DEFAULT 'pending',
	`progress` int DEFAULT 0,
	`sort_order` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `promotion_phases_id` PRIMARY KEY(`id`)
);
