CREATE TABLE IF NOT EXISTS `budget_tracking` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `marketplace` varchar(20) NOT NULL DEFAULT 'US',
  `batch_id` varchar(64) NOT NULL,
  `total_budget_before` decimal(12,2),
  `total_budget_after` decimal(12,2),
  `campaign_count` int DEFAULT 0,
  `baseline_spend` decimal(12,2),
  `baseline_sales` decimal(12,2),
  `baseline_acos` decimal(8,4),
  `baseline_roas` decimal(8,4),
  `baseline_orders` int DEFAULT 0,
  `budget_user_decision` enum('accepted','modified','rejected','partial') NOT NULL DEFAULT 'accepted',
  `user_notes` text,
  `campaign_decisions` text,
  `followup_spend` decimal(12,2),
  `followup_sales` decimal(12,2),
  `followup_acos` decimal(8,4),
  `followup_roas` decimal(8,4),
  `followup_orders` int,
  `followup_evaluated_at` timestamp,
  `effect_summary` text,
  `effect_score` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `budget_tracking_id` PRIMARY KEY(`id`)
);
