CREATE TABLE `data_imports` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `source_type` enum('lingxing','saihu') NOT NULL,
  `file_name` varchar(500) NOT NULL,
  `file_url` text,
  `week_start_date` varchar(10) NOT NULL,
  `week_end_date` varchar(10) NOT NULL,
  `total_rows` int DEFAULT 0,
  `imported_rows` int DEFAULT 0,
  `skipped_rows` int DEFAULT 0,
  `import_status` enum('pending','parsing','previewing','importing','completed','failed') NOT NULL DEFAULT 'pending',
  `error_message` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `data_imports_id` PRIMARY KEY(`id`)
);

CREATE TABLE `lingxing_product_weekly` (
  `id` int AUTO_INCREMENT NOT NULL,
  `import_id` int NOT NULL,
  `user_id` int NOT NULL,
  `week_start_date` varchar(10) NOT NULL,
  `week_end_date` varchar(10) NOT NULL,
  `asin` varchar(20),
  `parent_asin` varchar(20),
  `msku` varchar(200),
  `store_name` varchar(200),
  `country` varchar(50),
  `title` varchar(1000),
  `price` varchar(50),
  `operator` varchar(200),
  `product_name` varchar(500),
  `sku` varchar(200),
  `brand` varchar(200),
  `category1` varchar(200),
  `category2` varchar(200),
  `category3` varchar(200),
  `auto_tag` varchar(500),
  `listing_tag` varchar(500),
  `created_time` varchar(50),
  `sales_qty` int DEFAULT 0,
  `sales_amount` decimal(14,2) DEFAULT '0',
  `order_qty` int DEFAULT 0,
  `net_sales_amount` decimal(14,2) DEFAULT '0',
  `sales_qty_mom` varchar(20),
  `sales_amount_mom` varchar(20),
  `order_qty_mom` varchar(20),
  `sales_qty_yoy` varchar(20),
  `sales_amount_yoy` varchar(20),
  `order_qty_yoy` varchar(20),
  `avg_sales_qty` decimal(10,1) DEFAULT '0',
  `avg_price` varchar(50),
  `b2b_sales_qty` int DEFAULT 0,
  `b2b_sales_amount` decimal(14,2) DEFAULT '0',
  `b2b_order_qty` int DEFAULT 0,
  `promo_sales_qty` int DEFAULT 0,
  `promo_sales_amount` decimal(14,2) DEFAULT '0',
  `promo_order_qty` int DEFAULT 0,
  `promo_discount` decimal(12,2) DEFAULT '0',
  `fbm_buyer_shipping` decimal(12,2) DEFAULT '0',
  `bsr_main` varchar(100),
  `bsr_sub` varchar(100),
  `settlement_profit` decimal(14,2) DEFAULT '0',
  `order_profit` decimal(14,2) DEFAULT '0',
  `settlement_profit_margin` varchar(20),
  `order_profit_margin` varchar(20),
  `roi` varchar(20),
  `refund_qty` int DEFAULT 0,
  `refund_amount` decimal(12,2) DEFAULT '0',
  `refund_rate` varchar(20),
  `return_qty` int DEFAULT 0,
  `return_rate` varchar(20),
  `rating` varchar(10),
  `review_count` int DEFAULT 0,
  `review_rate` varchar(20),
  `fbm_available` int DEFAULT 0,
  `fba_available` int DEFAULT 0,
  `fba_transfer_pending` int DEFAULT 0,
  `fba_transferring` int DEFAULT 0,
  `fba_inbound` int DEFAULT 0,
  `fba_total` int DEFAULT 0,
  `fba_pending_ship` int DEFAULT 0,
  `fba_in_transit` int DEFAULT 0,
  `fba_plan_inbound` int DEFAULT 0,
  `fba_unavailable` int DEFAULT 0,
  `available_stock` int DEFAULT 0,
  `fba_days_of_supply` int DEFAULT 0,
  `fbm_days_of_supply` int DEFAULT 0,
  `awd_in_stock` int DEFAULT 0,
  `awd_available` int DEFAULT 0,
  `awd_pending_ship` int DEFAULT 0,
  `awd_in_transit` int DEFAULT 0,
  `overseas_available` int DEFAULT 0,
  `local_available` int DEFAULT 0,
  `purchase_qty` int DEFAULT 0,
  `monthly_stock_sales_ratio` varchar(50),
  `stockout_date` varchar(50),
  `sessions_browser` int DEFAULT 0,
  `sessions_browser_pct` varchar(20),
  `sessions_mobile` int DEFAULT 0,
  `sessions_mobile_pct` varchar(20),
  `sessions_total` int DEFAULT 0,
  `sessions_pct` varchar(20),
  `unit_sessions_pct` varchar(20),
  `pv_browser` int DEFAULT 0,
  `pv_browser_pct` varchar(20),
  `pv_mobile` int DEFAULT 0,
  `pv_mobile_pct` varchar(20),
  `pv_total` int DEFAULT 0,
  `pv_pct` varchar(20),
  `cvr` varchar(20),
  `sales_cvr` varchar(20),
  `buybox_rate` varchar(20),
  `ad_impressions` int DEFAULT 0,
  `ad_clicks` int DEFAULT 0,
  `ad_spend` decimal(14,2) DEFAULT '0',
  `sp_ad_spend` decimal(14,2) DEFAULT '0',
  `sb_ad_spend` decimal(14,2) DEFAULT '0',
  `sbv_ad_spend` decimal(14,2) DEFAULT '0',
  `sd_ad_spend` decimal(14,2) DEFAULT '0',
  `st_ad_spend` decimal(14,2) DEFAULT '0',
  `live_ad_spend` decimal(14,2) DEFAULT '0',
  `ad_sales` decimal(14,2) DEFAULT '0',
  `sp_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_ad_sales` decimal(14,2) DEFAULT '0',
  `sbv_ad_sales` decimal(14,2) DEFAULT '0',
  `sd_ad_sales` decimal(14,2) DEFAULT '0',
  `ad_orders` int DEFAULT 0,
  `sp_ad_orders` int DEFAULT 0,
  `sb_ad_orders` int DEFAULT 0,
  `sbv_ad_orders` int DEFAULT 0,
  `sd_ad_orders` int DEFAULT 0,
  `ad_order_pct` varchar(20),
  `direct_sales` decimal(14,2) DEFAULT '0',
  `direct_orders` int DEFAULT 0,
  `ctr` varchar(20),
  `ad_cvr` varchar(20),
  `cpc` varchar(20),
  `cpm` varchar(20),
  `roas` varchar(20),
  `acos` varchar(20),
  `tacos` varchar(20),
  `acoas` varchar(20),
  `asoas` varchar(20),
  `cpo` varchar(20),
  `cpu` varchar(20),
  `organic_clicks` int DEFAULT 0,
  `organic_orders` int DEFAULT 0,
  `organic_cvr` varchar(20),
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `lingxing_product_weekly_id` PRIMARY KEY(`id`),
  KEY `idx_lx_import` (`import_id`),
  KEY `idx_lx_parent_asin_week` (`parent_asin`, `week_start_date`),
  KEY `idx_lx_user_week` (`user_id`, `week_start_date`)
);

CREATE TABLE `saihu_product_weekly` (
  `id` int AUTO_INCREMENT NOT NULL,
  `import_id` int NOT NULL,
  `user_id` int NOT NULL,
  `week_start_date` varchar(10) NOT NULL,
  `week_end_date` varchar(10) NOT NULL,
  `currency` varchar(10),
  `image_url` text,
  `asin` varchar(20),
  `title` varchar(1000),
  `parent_asin` varchar(20),
  `msku` varchar(500),
  `product_name` varchar(500),
  `sku` varchar(500),
  `store_name` varchar(200),
  `site` varchar(50),
  `category` varchar(500),
  `brand` varchar(200),
  `operator` varchar(200),
  `developer` varchar(200),
  `product_tag` varchar(500),
  `listing_date` varchar(50),
  `sales_3d` int DEFAULT 0,
  `sales_7d` int DEFAULT 0,
  `sales_14d` int DEFAULT 0,
  `sales_30d` int DEFAULT 0,
  `sales_60d` int DEFAULT 0,
  `sales_90d` int DEFAULT 0,
  `gross_profit` decimal(14,2) DEFAULT '0',
  `gross_margin` decimal(8,4) DEFAULT '0',
  `avg_gross_profit` decimal(10,2) DEFAULT '0',
  `sales_qty` int DEFAULT 0,
  `fba_sales_qty` int DEFAULT 0,
  `fbm_sales_qty` int DEFAULT 0,
  `avg_sales_qty` decimal(10,1) DEFAULT '0',
  `promo_sales_qty` int DEFAULT 0,
  `b2b_sales_qty` int DEFAULT 0,
  `b2b_order_qty` int DEFAULT 0,
  `vine_sales_qty` int DEFAULT 0,
  `multi_channel_sales_qty` int DEFAULT 0,
  `order_qty` int DEFAULT 0,
  `promo_order_qty` int DEFAULT 0,
  `cancel_order_qty` int DEFAULT 0,
  `cancel_order_pct` decimal(8,4) DEFAULT '0',
  `sales_amount` decimal(14,2) DEFAULT '0',
  `net_sales_amount` decimal(14,2) DEFAULT '0',
  `promo_sales_amount` decimal(14,2) DEFAULT '0',
  `sales_revenue` decimal(14,2) DEFAULT '0',
  `avg_price` decimal(10,2) DEFAULT '0',
  `product_discount` decimal(12,2) DEFAULT '0',
  `fbm_buyer_shipping` decimal(12,2) DEFAULT '0',
  `b2b_sales_amount` decimal(14,2) DEFAULT '0',
  `refund_amount` decimal(12,2) DEFAULT '0',
  `refund_qty` int DEFAULT 0,
  `refund_rate` decimal(8,4) DEFAULT '0',
  `return_qty` int DEFAULT 0,
  `fba_return_qty` int DEFAULT 0,
  `fbm_return_qty` int DEFAULT 0,
  `return_rate` decimal(8,4) DEFAULT '0',
  `fba_return_rate` decimal(8,4) DEFAULT '0',
  `fbm_return_rate` decimal(8,4) DEFAULT '0',
  `exchange_qty` int DEFAULT 0,
  `exchange_rate` decimal(8,4) DEFAULT '0',
  `test_sales_amount` decimal(12,2) DEFAULT '0',
  `fba_available` int DEFAULT 0,
  `reserved_transfer` int DEFAULT 0,
  `reserved_processing` int DEFAULT 0,
  `inbound_receiving` int DEFAULT 0,
  `reserved_order` int DEFAULT 0,
  `inbound_processing` int DEFAULT 0,
  `inbound_shipped` int DEFAULT 0,
  `fba_unavailable` int DEFAULT 0,
  `investigating` int DEFAULT 0,
  `fba_usable` int DEFAULT 0,
  `fba_in_transit` int DEFAULT 0,
  `fba_days_of_supply` decimal(8,1) DEFAULT '0',
  `fbm_available` int DEFAULT 0,
  `fbm_days_of_supply` decimal(8,1),
  `awd_stock` int,
  `awd_available` int,
  `awd_reserved` int,
  `awd_in_transit` int,
  `awd_to_fba_in_transit` int,
  `suggested_replenish_qty` int,
  `local_warehouse_available` int,
  `overseas_warehouse_available` int,
  `age_0_to_30` int DEFAULT 0,
  `age_31_to_60` int DEFAULT 0,
  `age_61_to_90` int DEFAULT 0,
  `age_91_to_180` int DEFAULT 0,
  `age_181_to_270` int DEFAULT 0,
  `age_271_to_365` int DEFAULT 0,
  `age_365_plus` int DEFAULT 0,
  `sessions_mobile` int DEFAULT 0,
  `sessions_browser` int DEFAULT 0,
  `sessions_total` int DEFAULT 0,
  `pv_mobile` int DEFAULT 0,
  `pv_browser` int DEFAULT 0,
  `pv_total` int DEFAULT 0,
  `buybox_price` varchar(20),
  `buybox_rate` decimal(8,4),
  `cvr` decimal(8,4) DEFAULT '0',
  `order_cvr` decimal(8,4) DEFAULT '0',
  `bsr_sub` varchar(200),
  `bsr_main` varchar(200),
  `rating` decimal(3,1),
  `rating_count` int DEFAULT 0,
  `negative_review_count` int,
  `effective_review_count` int,
  `review_rate` decimal(8,4) DEFAULT '0',
  `organic_clicks` int DEFAULT 0,
  `organic_orders` int DEFAULT 0,
  `organic_cvr` decimal(8,4) DEFAULT '0',
  `organic_order_pct` decimal(8,4),
  `ad_impressions` int DEFAULT 0,
  `ad_clicks` int DEFAULT 0,
  `ad_click_rate` decimal(8,4) DEFAULT '0',
  `ad_cvr` decimal(8,4) DEFAULT '0',
  `cpc_ad_cvr` decimal(8,4) DEFAULT '0',
  `vcpm_ad_cvr` decimal(8,4) DEFAULT '0',
  `ad_spend` decimal(14,2) DEFAULT '0',
  `sp_ad_spend` decimal(14,2) DEFAULT '0',
  `sb_collection_ad_spend` decimal(14,2) DEFAULT '0',
  `sb_store_ad_spend` decimal(14,2) DEFAULT '0',
  `sb_video_ad_spend` decimal(14,2) DEFAULT '0',
  `sd_ad_spend` decimal(14,2) DEFAULT '0',
  `cpc` decimal(10,2) DEFAULT '0',
  `cpa` decimal(10,2) DEFAULT '0',
  `cpo` decimal(10,2) DEFAULT '0',
  `cpu` decimal(10,2) DEFAULT '0',
  `acos` decimal(8,4) DEFAULT '0',
  `sp_acos` decimal(8,4) DEFAULT '0',
  `sb_collection_acos` decimal(8,4) DEFAULT '0',
  `sb_store_acos` decimal(8,4) DEFAULT '0',
  `sb_video_acos` decimal(8,4) DEFAULT '0',
  `sd_acos` decimal(8,4) DEFAULT '0',
  `acoas` decimal(8,4) DEFAULT '0',
  `asoas` decimal(8,4) DEFAULT '0',
  `ad_sales_qty` int DEFAULT 0,
  `ad_orders` int DEFAULT 0,
  `sp_ad_orders` int DEFAULT 0,
  `sb_collection_ad_orders` int DEFAULT 0,
  `sb_store_ad_orders` int DEFAULT 0,
  `sb_video_ad_orders` int DEFAULT 0,
  `sd_ad_orders` int DEFAULT 0,
  `ad_order_pct` decimal(8,4) DEFAULT '0',
  `ad_sales_amount` decimal(14,2) DEFAULT '0',
  `sp_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_collection_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_store_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_video_ad_sales` decimal(14,2) DEFAULT '0',
  `sd_ad_sales` decimal(14,2) DEFAULT '0',
  `self_ad_sales` decimal(14,2) DEFAULT '0',
  `sp_self_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_collection_self_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_store_self_ad_sales` decimal(14,2) DEFAULT '0',
  `sb_video_self_ad_sales` decimal(14,2) DEFAULT '0',
  `sd_self_ad_sales` decimal(14,2) DEFAULT '0',
  `self_ad_orders` int DEFAULT 0,
  `sp_self_ad_orders` int DEFAULT 0,
  `sb_collection_self_ad_orders` int DEFAULT 0,
  `sb_store_self_ad_orders` int DEFAULT 0,
  `sb_video_self_ad_orders` int DEFAULT 0,
  `sd_self_ad_orders` int DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `saihu_product_weekly_id` PRIMARY KEY(`id`),
  KEY `idx_sh_import` (`import_id`),
  KEY `idx_sh_parent_asin_week` (`parent_asin`, `week_start_date`),
  KEY `idx_sh_asin_week` (`asin`, `week_start_date`),
  KEY `idx_sh_user_week` (`user_id`, `week_start_date`)
);
