-- Operations and advertising tables that predate the governed migration ledger.
-- Workspace columns are intentionally added by 0116_ops_workspace_isolation.sql.

CREATE TABLE IF NOT EXISTS `meeting_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`title` varchar(300),
	`audio_url` text,
	`transcript` text,
	`extracted_tasks` text,
	`meeting_status` enum('uploading','transcribing','extracting','done','error') NOT NULL DEFAULT 'uploading',
	`error_message` text,
	`duration` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meeting_records_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `operator_name_mappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`external_name` varchar(200) NOT NULL,
	`source_type` enum('lingxing','saihu','all') NOT NULL DEFAULT 'all',
	`system_user_name` varchar(200),
	`system_user_id` int,
	`is_confirmed` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `operator_name_mappings_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ops_import_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`import_type` enum('plan','review') NOT NULL,
	`file_name` varchar(255) NOT NULL,
	`total_count` int NOT NULL DEFAULT 0,
	`created_count` int NOT NULL DEFAULT 0,
	`updated_count` int NOT NULL DEFAULT 0,
	`skipped_count` int NOT NULL DEFAULT 0,
	`record_ids` text,
	`parent_asins` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ops_import_history_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `production_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`parent_asin` varchar(50) NOT NULL,
	`marketplace` varchar(10) DEFAULT 'US',
	`production_time_days` int DEFAULT 15,
	`shipping_time_days` int DEFAULT 30,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `production_config_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_campaign_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`week_start_date` varchar(10) NOT NULL,
	`week_end_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) NOT NULL,
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500) NOT NULL,
	`effective_status` varchar(50),
	`budget` decimal(10,2),
	`impressions` int DEFAULT 0,
	`impression_share` varchar(20),
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`direct_sales` decimal(12,2),
	`indirect_sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`direct_orders` int DEFAULT 0,
	`indirect_orders` int DEFAULT 0,
	`indirect_order_ratio` decimal(6,4),
	`cpa` decimal(10,2),
	`cvr` decimal(8,4),
	`avg_order_value` decimal(10,2),
	`direct_avg_order_value` decimal(10,2),
	`indirect_avg_order_value` decimal(10,2),
	`brand_new_orders` int DEFAULT 0,
	`brand_new_cvr` decimal(8,4),
	`brand_new_sales` decimal(12,2),
	`brand_new_sales_qty` int DEFAULT 0,
	`ad_sales_qty` int DEFAULT 0,
	`direct_sales_qty` int DEFAULT 0,
	`indirect_sales_qty` int DEFAULT 0,
	`vcpm` decimal(10,2),
	`viewable_impressions` int DEFAULT 0,
	`dpv` int DEFAULT 0,
	`five_sec_views` int DEFAULT 0,
	`five_sec_view_rate` decimal(8,4),
	`video_quarter` int DEFAULT 0,
	`video_half` int DEFAULT 0,
	`video_three_quarter` int DEFAULT 0,
	`video_complete` int DEFAULT 0,
	`video_unmute` int DEFAULT 0,
	`vtr` decimal(8,4),
	`vctr` decimal(8,4),
	`brand_search_count` int DEFAULT 0,
	`avg_reach` decimal(8,2),
	`cumulative_reach` int DEFAULT 0,
	`tags` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_campaign_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_clinic_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`portfolio_names` text,
	`date_range_start` varchar(10),
	`date_range_end` varchar(10),
	`symptom_category` varchar(50),
	`symptom_description` text,
	`additional_context` text,
	`diagnosis` text,
	`prescription` text,
	`user_edits` text,
	`status` enum('consulting','diagnosed','treating','resolved','archived') NOT NULL DEFAULT 'consulting',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_clinic_records_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_daily_business_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`child_asin` varchar(20),
	`report_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`sku` varchar(100),
	`product_name` varchar(500),
	`sessions` int DEFAULT 0,
	`session_percentage` decimal(8,4),
	`page_views` int DEFAULT 0,
	`page_views_percentage` decimal(8,4),
	`buy_box_percentage` decimal(8,4),
	`units_ordered` int DEFAULT 0,
	`units_ordered_b2b` int DEFAULT 0,
	`unit_session_percentage` decimal(8,4),
	`unit_session_percentage_b2b` decimal(8,4),
	`ordered_product_sales` decimal(12,2),
	`ordered_product_sales_b2b` decimal(12,2),
	`total_order_items` int DEFAULT 0,
	`total_order_items_b2b` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_daily_business_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_daily_impression_share_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`report_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) DEFAULT 'SP',
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500),
	`ad_group_name` varchar(500),
	`targeting` varchar(500),
	`search_term` varchar(500),
	`impression_share` decimal(8,4),
	`impression_rank` int,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`acos` decimal(8,4),
	`orders` int DEFAULT 0,
	`top_competitor_share` decimal(8,4),
	`top_competitor_asin` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_daily_impression_share_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_daily_placement_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`report_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) NOT NULL,
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500) NOT NULL,
	`placement` varchar(100) NOT NULL,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`direct_sales` decimal(12,2),
	`indirect_sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`direct_orders` int DEFAULT 0,
	`indirect_orders` int DEFAULT 0,
	`cvr` decimal(8,4),
	`cpa` decimal(10,2),
	`brand_new_orders` int DEFAULT 0,
	`brand_new_sales` decimal(12,2),
	`viewable_impressions` int DEFAULT 0,
	`vtr` decimal(8,4),
	`vctr` decimal(8,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_daily_placement_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_daily_sb_benchmark_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`report_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`campaign_name` varchar(500) NOT NULL,
	`ad_format` varchar(50),
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`dpv` int DEFAULT 0,
	`new_to_brand_orders` int DEFAULT 0,
	`new_to_brand_sales` decimal(12,2),
	`new_to_brand_rate` decimal(8,4),
	`benchmark_ctr` decimal(8,4),
	`benchmark_cpc` decimal(10,2),
	`benchmark_acos` decimal(8,4),
	`benchmark_roas` decimal(8,2),
	`benchmark_cvr` decimal(8,4),
	`benchmark_dpv_rate` decimal(8,4),
	`benchmark_new_to_brand_rate` decimal(8,4),
	`ctr_vs_benchmark` varchar(20),
	`cpc_vs_benchmark` varchar(20),
	`acos_vs_benchmark` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_daily_sb_benchmark_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_daily_search_term_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`report_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) NOT NULL,
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500),
	`ad_group_name` varchar(500),
	`keyword` varchar(500),
	`match_type` varchar(20),
	`targeting` varchar(500),
	`search_term` varchar(500) NOT NULL,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`direct_sales` decimal(12,2),
	`indirect_sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`direct_orders` int DEFAULT 0,
	`indirect_orders` int DEFAULT 0,
	`cvr` decimal(8,4),
	`cpa` decimal(10,2),
	`avg_order_value` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_daily_search_term_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_diagnoses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`portfolio_names` text,
	`date_range_start` varchar(10) NOT NULL,
	`date_range_end` varchar(10) NOT NULL,
	`diagnosis_result` text,
	`overall_verdict` text,
	`priority_actions` text,
	`warning` text,
	`user_edits` text,
	`status` enum('draft','confirmed','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_diagnoses_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_hourly_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`hour` int NOT NULL,
	`report_date` varchar(10),
	`currency` varchar(10),
	`account_name` varchar(200),
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500),
	`campaign_id` varchar(100),
	`ad_group_name` varchar(500),
	`ad_group_id` varchar(100),
	`targeting_value` varchar(500),
	`search_term` varchar(500),
	`promoted_sku` varchar(100),
	`promoted_asin` varchar(20),
	`placement_name` varchar(200),
	`placement_classification` varchar(100),
	`impressions` int DEFAULT 0,
	`invalid_impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`invalid_clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`cpm` decimal(10,2),
	`vcpm` decimal(10,2),
	`vctr` decimal(8,4),
	`spend` decimal(12,2),
	`purchases` int DEFAULT 0,
	`sales` decimal(12,2),
	`cost_per_purchase` decimal(10,2),
	`purchase_rate` decimal(8,4),
	`roas` decimal(8,2),
	`click_purchases` int DEFAULT 0,
	`click_roas` decimal(8,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_hourly_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_keyword_tiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`portfolio_names` text,
	`date_range_start` varchar(10) NOT NULL,
	`date_range_end` varchar(10) NOT NULL,
	`keyword` varchar(500) NOT NULL,
	`tier` varchar(20) NOT NULL,
	`role` varchar(20),
	`current_performance` varchar(20),
	`daily_trend` varchar(20),
	`anomaly_dates` text,
	`action` text,
	`bid_suggestion` text,
	`priority` varchar(10),
	`reason` text,
	`user_edited` int DEFAULT 0,
	`user_action` text,
	`status` enum('pending','confirmed','ignored') NOT NULL DEFAULT 'pending',
	`batch_id` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_keyword_tiers_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_order_hourly` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`order_id` varchar(50) NOT NULL,
	`order_status` varchar(50),
	`order_type` varchar(20),
	`order_date` timestamp NOT NULL,
	`order_hour` int NOT NULL,
	`order_day_of_week` int NOT NULL,
	`order_date_str` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`asin` varchar(20),
	`sku` varchar(100),
	`msku` varchar(100),
	`product_name` varchar(500),
	`quantity` int DEFAULT 1,
	`unit_price` decimal(10,2),
	`sales_revenue` decimal(10,2),
	`item_price` decimal(10,2),
	`currency` varchar(10),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_order_hourly_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_placement_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`week_start_date` varchar(10) NOT NULL,
	`week_end_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) NOT NULL,
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500) NOT NULL,
	`placement` varchar(100) NOT NULL,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`direct_sales` decimal(12,2),
	`indirect_sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`direct_orders` int DEFAULT 0,
	`indirect_orders` int DEFAULT 0,
	`indirect_order_ratio` decimal(6,4),
	`cpa` decimal(10,2),
	`cvr` decimal(8,4),
	`avg_order_value` decimal(10,2),
	`direct_avg_order_value` decimal(10,2),
	`indirect_avg_order_value` decimal(10,2),
	`brand_new_orders` int DEFAULT 0,
	`brand_new_cvr` decimal(8,4),
	`brand_new_sales` decimal(12,2),
	`brand_new_sales_qty` int DEFAULT 0,
	`ad_sales_qty` int DEFAULT 0,
	`direct_sales_qty` int DEFAULT 0,
	`indirect_sales_qty` int DEFAULT 0,
	`viewable_impressions` int DEFAULT 0,
	`dpv` int DEFAULT 0,
	`five_sec_views` int DEFAULT 0,
	`five_sec_view_rate` decimal(8,4),
	`video_quarter` int DEFAULT 0,
	`video_half` int DEFAULT 0,
	`video_three_quarter` int DEFAULT 0,
	`video_complete` int DEFAULT 0,
	`video_unmute` int DEFAULT 0,
	`vtr` decimal(8,4),
	`vctr` decimal(8,4),
	`brand_search_count` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_placement_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_product_stages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`portfolio_names` text,
	`parent_asin` varchar(20),
	`date_range_start` varchar(10) NOT NULL,
	`date_range_end` varchar(10) NOT NULL,
	`stage` varchar(20) NOT NULL,
	`confidence` int DEFAULT 0,
	`evidence` text,
	`red_flags` text,
	`daily_highlights` text,
	`strategy` text,
	`transition_signals` text,
	`user_edits` text,
	`status` enum('draft','confirmed','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_product_stages_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_report_analysis_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`report_type` varchar(30) NOT NULL,
	`portfolio_names` text,
	`date_range_start` varchar(10) NOT NULL,
	`date_range_end` varchar(10) NOT NULL,
	`analysis_result` text,
	`action_items` text,
	`user_edits` text,
	`status` enum('draft','confirmed','archived') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_report_analysis_records_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_report_uploads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`report_type` enum('search_term','campaign','placement','hourly','order','dsp','daily_placement','daily_search_term','daily_impression_share','daily_sb_benchmark','daily_business') NOT NULL,
	`file_name` varchar(500) NOT NULL,
	`file_url` text,
	`week_start_date` varchar(10),
	`week_end_date` varchar(10),
	`date_label` varchar(50),
	`total_rows` int DEFAULT 0,
	`imported_rows` int DEFAULT 0,
	`store_name` varchar(200),
	`upload_status` enum('pending','parsing','completed','failed') NOT NULL DEFAULT 'pending',
	`error_message` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_report_uploads_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_search_term_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`upload_id` int NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int,
	`parent_asin` varchar(20),
	`week_start_date` varchar(10) NOT NULL,
	`week_end_date` varchar(10) NOT NULL,
	`store_name` varchar(200),
	`country` varchar(50),
	`ad_type` varchar(10) NOT NULL,
	`portfolio_name` varchar(300),
	`campaign_name` varchar(500),
	`ad_group_name` varchar(500),
	`keyword` varchar(500),
	`match_type` varchar(20),
	`targeting` varchar(500),
	`search_term` varchar(500) NOT NULL,
	`impressions` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`ctr` decimal(8,4),
	`cpc` decimal(10,2),
	`spend` decimal(12,2),
	`sales` decimal(12,2),
	`direct_sales` decimal(12,2),
	`indirect_sales` decimal(12,2),
	`acos` decimal(8,4),
	`roas` decimal(8,2),
	`orders` int DEFAULT 0,
	`direct_orders` int DEFAULT 0,
	`indirect_orders` int DEFAULT 0,
	`indirect_order_ratio` decimal(6,4),
	`cpa` decimal(10,2),
	`cvr` decimal(8,4),
	`avg_order_value` decimal(10,2),
	`direct_avg_order_value` decimal(10,2),
	`indirect_avg_order_value` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_search_term_reports_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `ad_sop_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`portfolio_names` text,
	`period` varchar(20) NOT NULL,
	`category` varchar(50) NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`evidence` text,
	`priority` varchar(10),
	`status` enum('pending','in_progress','completed','skipped') NOT NULL DEFAULT 'pending',
	`completedAt` timestamp,
	`completed_note` text,
	`source_module` varchar(30),
	`source_record_id` int,
	`due_date` varchar(10),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_sop_tasks_id` PRIMARY KEY(`id`)
);
