CREATE TABLE IF NOT EXISTS `ops_asin_lifecycle_statuses` (
  `workspaceId` INT NOT NULL DEFAULT 1,
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `asin` VARCHAR(20) NOT NULL,
  `parent_asin` VARCHAR(20) NULL,
  `store_name` VARCHAR(200) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `status` ENUM('active','discontinued') NOT NULL DEFAULT 'active',
  `reason` VARCHAR(80) NULL,
  `evidence_start_date` VARCHAR(10) NULL,
  `evidence_end_date` VARCHAR(10) NULL,
  `evidence_days` INT NOT NULL DEFAULT 0,
  `evidence_sales_qty` INT NOT NULL DEFAULT 0,
  `evidence_profit` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `evidence_max_inventory` INT NOT NULL DEFAULT 0,
  `changed_by` INT NULL,
  `changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `restored_at` TIMESTAMP NULL,
  `restore_reason` VARCHAR(500) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `ops_asin_lifecycle_unique` (`workspaceId`, `asin`, `store_name`, `country`),
  KEY `ops_asin_lifecycle_asin_store_country_idx` (`workspaceId`, `asin`, `store_name`, `country`),
  KEY `ops_asin_lifecycle_status_idx` (`workspaceId`, `status`)
);
