CREATE TABLE IF NOT EXISTS `emperor_conversations` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `workspaceId` INT NULL,
  `conversationId` VARCHAR(80) NOT NULL UNIQUE,
  `userId` INT NOT NULL,
  `projectId` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `status` ENUM('draft','planning','awaiting_plan_confirmation','running','waiting_human','completed','failed','canceled','archived') NOT NULL DEFAULT 'draft',
  `activePlanId` VARCHAR(80) NULL,
  `lastTraceId` VARCHAR(80) NULL,
  `metadata` JSON NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `emperor_conversations_workspace_status_idx` (`workspaceId`,`status`),
  INDEX `emperor_conversations_user_created_idx` (`userId`,`createdAt`)
);

CREATE TABLE IF NOT EXISTS `emperor_conversation_messages` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `workspaceId` INT NULL,
  `messageId` VARCHAR(80) NOT NULL UNIQUE,
  `conversationId` VARCHAR(80) NOT NULL,
  `role` ENUM('user','assistant','system','tool') NOT NULL,
  `status` ENUM('draft','streaming','completed','failed','canceled') NOT NULL DEFAULT 'completed',
  `content` TEXT NOT NULL,
  `structuredContent` JSON NULL,
  `planId` VARCHAR(80) NULL,
  `stepId` VARCHAR(80) NULL,
  `createdBy` INT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `emperor_conversation_messages_conversation_created_idx` (`conversationId`,`createdAt`),
  INDEX `emperor_conversation_messages_workspace_created_idx` (`workspaceId`,`createdAt`)
);

CREATE TABLE IF NOT EXISTS `emperor_conversation_attachments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `workspaceId` INT NULL,
  `attachmentId` VARCHAR(80) NOT NULL UNIQUE,
  `conversationId` VARCHAR(80) NOT NULL,
  `messageId` VARCHAR(80) NULL,
  `storageObjectId` INT NULL,
  `artifactId` VARCHAR(80) NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(128) NOT NULL,
  `sizeBytes` BIGINT NULL,
  `contentHash` VARCHAR(64) NULL,
  `contextPolicy` ENUM('summary_only','extracted_text','image_vision','blocked') NOT NULL DEFAULT 'summary_only',
  `scanStatus` ENUM('pending','ready','blocked','failed') NOT NULL DEFAULT 'pending',
  `contextSummary` TEXT NULL,
  `metadata` JSON NULL,
  `createdBy` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `emperor_conversation_attachments_conversation_idx` (`conversationId`),
  INDEX `emperor_conversation_attachments_storage_idx` (`storageObjectId`),
  INDEX `emperor_conversation_attachments_artifact_idx` (`artifactId`)
);

CREATE TABLE IF NOT EXISTS `emperor_conversation_plans` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `workspaceId` INT NULL,
  `planId` VARCHAR(80) NOT NULL UNIQUE,
  `conversationId` VARCHAR(80) NOT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `status` ENUM('draft','proposed','approved','executing','completed','failed','canceled','superseded') NOT NULL DEFAULT 'draft',
  `goal` TEXT NOT NULL,
  `assumptions` JSON NULL,
  `planJson` JSON NOT NULL,
  `riskSummary` JSON NULL,
  `approvedBy` INT NULL,
  `approvedAt` TIMESTAMP NULL,
  `canceledAt` TIMESTAMP NULL,
  `createdBy` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `emperor_conversation_plans_conversation_version_uq` (`conversationId`,`version`),
  INDEX `emperor_conversation_plans_workspace_status_idx` (`workspaceId`,`status`)
);

CREATE TABLE IF NOT EXISTS `emperor_conversation_plan_steps` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `workspaceId` INT NULL,
  `stepId` VARCHAR(80) NOT NULL UNIQUE,
  `planId` VARCHAR(80) NOT NULL,
  `sequence` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `capabilityType` ENUM('skill','agent','tool') NOT NULL,
  `capabilitySlug` VARCHAR(128) NOT NULL,
  `input` JSON NULL,
  `riskLevel` ENUM('L0','L1','L2','L3') NOT NULL DEFAULT 'L1',
  `approvalRequired` TINYINT NOT NULL DEFAULT 0,
  `approvalState` ENUM('not_required','pending','approved','rejected','skipped') NOT NULL DEFAULT 'not_required',
  `status` ENUM('pending','ready','running','waiting_human','succeeded','skipped','failed','canceled') NOT NULL DEFAULT 'pending',
  `skillRunId` VARCHAR(80) NULL,
  `agentRunId` VARCHAR(80) NULL,
  `toolRunId` VARCHAR(80) NULL,
  `traceId` VARCHAR(80) NULL,
  `reviewRequestId` VARCHAR(80) NULL,
  `errorMessage` TEXT NULL,
  `metadata` JSON NULL,
  `startedAt` TIMESTAMP NULL,
  `completedAt` TIMESTAMP NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `emperor_conversation_plan_steps_plan_sequence_uq` (`planId`,`sequence`),
  INDEX `emperor_conversation_plan_steps_workspace_status_idx` (`workspaceId`,`status`),
  INDEX `emperor_conversation_plan_steps_trace_idx` (`traceId`)
);
