CREATE TABLE IF NOT EXISTS `knowledge_distillation_projects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspaceId` int NOT NULL,
  `projectKey` varchar(80) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` enum('setup','ready','draft_review','paused','archived') NOT NULL DEFAULT 'setup',
  `profile` json NOT NULL,
  `sourcePolicy` json NOT NULL,
  `createdBy` int NOT NULL,
  `updatedBy` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_project_workspace_key` (`workspaceId`,`projectKey`),
  KEY `idx_kdistill_project_workspace_status` (`workspaceId`,`status`)
);

CREATE TABLE IF NOT EXISTS `knowledge_distillation_sources` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sourceKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `distillationProjectId` int NOT NULL,
  `sourceDomain` enum('products','listings','images','skills','videos') NOT NULL,
  `sourceTable` varchar(128) NOT NULL,
  `sourceRowId` varchar(128) NOT NULL,
  `sourceContentHash` varchar(64) NOT NULL,
  `sourceStatus` enum('eligible','invalidated','excluded') NOT NULL DEFAULT 'eligible',
  `sourceSummary` text,
  `sourceMetadata` json,
  `selectedBy` int NOT NULL,
  `confirmedBy` int,
  `confirmedAt` timestamp NULL,
  `invalidatedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_source_key` (`sourceKey`),
  UNIQUE KEY `uq_kdistill_source_identity` (`distillationProjectId`,`sourceTable`,`sourceRowId`,`sourceContentHash`),
  KEY `idx_kdistill_source_project_status` (`distillationProjectId`,`sourceStatus`),
  KEY `idx_kdistill_source_workspace_domain` (`workspaceId`,`sourceDomain`)
);

CREATE TABLE IF NOT EXISTS `knowledge_distillation_evidence` (
  `id` int NOT NULL AUTO_INCREMENT,
  `evidenceKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `distillationProjectId` int NOT NULL,
  `sourceKey` varchar(80) NOT NULL,
  `evidenceType` enum('specification','benefit','compatibility','proof','objection','visual_pattern','compliance','brand') NOT NULL,
  `claim` text NOT NULL,
  `normalizedAttributes` json NOT NULL,
  `confidence` decimal(4,3) NOT NULL DEFAULT 0.000,
  `status` enum('draft','approved','rejected','invalidated') NOT NULL DEFAULT 'draft',
  `reviewerUserId` int,
  `reviewNote` text,
  `createdBy` int NOT NULL,
  `approvedAt` timestamp NULL,
  `invalidatedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_evidence_key` (`evidenceKey`),
  UNIQUE KEY `uq_kdistill_evidence_project_source_claim` (`distillationProjectId`,`sourceKey`,`claim`(191)),
  KEY `idx_kdistill_evidence_project_status` (`distillationProjectId`,`status`)
);

CREATE TABLE IF NOT EXISTS `knowledge_skill_drafts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `draftKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `distillationProjectId` int NOT NULL,
  `skillTypeKey` varchar(128) NOT NULL,
  `title` varchar(255) NOT NULL,
  `profile` json NOT NULL,
  `manifestDraft` json NOT NULL,
  `evidenceKeys` json NOT NULL,
  `sourceFingerprint` varchar(64) NOT NULL,
  `parentDraftKey` varchar(80),
  `proposedSkillSlug` varchar(128),
  `proposedSkillVersion` int,
  `status` enum('draft','conflict','review','approved','rejected','published','superseded') NOT NULL DEFAULT 'draft',
  `conflictReport` json,
  `reviewSummary` text,
  `artifactId` varchar(80),
  `createdBy` int NOT NULL,
  `reviewedBy` int,
  `reviewedAt` timestamp NULL,
  `publishedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_draft_key` (`draftKey`),
  UNIQUE KEY `uq_kdistill_draft_project_fingerprint` (`distillationProjectId`,`skillTypeKey`,`sourceFingerprint`),
  KEY `idx_kdistill_draft_project_status` (`distillationProjectId`,`status`),
  KEY `idx_kdistill_draft_workspace_type` (`workspaceId`,`skillTypeKey`)
);

CREATE TABLE IF NOT EXISTS `knowledge_skill_review_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `eventKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `distillationProjectId` int NOT NULL,
  `draftKey` varchar(80),
  `eventType` enum('source_selected','source_invalidated','evidence_approved','draft_created','draft_edited','conflict_detected','review_requested','approved','rejected','published','rolled_back') NOT NULL,
  `beforeSnapshot` json,
  `afterSnapshot` json,
  `reason` text,
  `actorUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_review_event_key` (`eventKey`),
  KEY `idx_kdistill_review_project_created` (`distillationProjectId`,`createdAt`),
  KEY `idx_kdistill_review_draft_created` (`draftKey`,`createdAt`)
);

CREATE TABLE IF NOT EXISTS `knowledge_skill_feedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `feedbackKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `distillationProjectId` int,
  `skillSlug` varchar(128) NOT NULL,
  `skillVersion` int,
  `consumerDomain` enum('listing','image','other') NOT NULL,
  `consumerRef` varchar(192) NOT NULL,
  `outcome` enum('accepted','revised','rejected','published','issue') NOT NULL,
  `editDelta` json,
  `note` text,
  `recordedBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_kdistill_feedback_key` (`feedbackKey`),
  KEY `idx_kdistill_feedback_skill` (`workspaceId`,`skillSlug`,`createdAt`)
);

CREATE TABLE IF NOT EXISTS `knowledge_claim_ledgers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ledgerKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `businessProjectId` int,
  `listingId` int,
  `imageWorkflowSessionId` int,
  `profile` json NOT NULL,
  `claims` json NOT NULL,
  `status` enum('draft','review','locked','superseded','archived') NOT NULL DEFAULT 'draft',
  `artifactId` varchar(80),
  `version` int NOT NULL DEFAULT 1,
  `isCurrent` tinyint NOT NULL DEFAULT 1,
  `parentLedgerKey` varchar(80),
  `lockedBy` int,
  `lockedAt` timestamp NULL,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_claim_ledger_key` (`ledgerKey`),
  UNIQUE KEY `uq_claim_ledger_scope_version` (`workspaceId`,`businessProjectId`,`listingId`,`imageWorkflowSessionId`,`version`),
  KEY `idx_claim_ledger_workspace_project` (`workspaceId`,`businessProjectId`,`isCurrent`)
);

CREATE TABLE IF NOT EXISTS `knowledge_claim_ledger_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `linkKey` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `ledgerKey` varchar(80) NOT NULL,
  `claimKey` varchar(80) NOT NULL,
  `targetDomain` enum('listing','image','brand_story') NOT NULL,
  `targetType` varchar(64) NOT NULL,
  `targetRef` varchar(192) NOT NULL,
  `targetPosition` varchar(128),
  `status` enum('candidate','confirmed','locked','invalidated') NOT NULL DEFAULT 'candidate',
  `createdBy` int NOT NULL,
  `confirmedBy` int,
  `confirmedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_claim_ledger_link_key` (`linkKey`),
  UNIQUE KEY `uq_claim_ledger_link_target` (`ledgerKey`,`claimKey`,`targetDomain`,`targetRef`),
  KEY `idx_claim_ledger_link_ledger_status` (`ledgerKey`,`status`)
);
