CREATE TABLE IF NOT EXISTS `acquisition_provider_profiles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `profile_key` varchar(64) NOT NULL,
  `provider_code` varchar(64) NOT NULL,
  `display_name` varchar(128) NOT NULL,
  `status` enum('draft','qualification_pending','active','paused','rejected') NOT NULL DEFAULT 'draft',
  `secret_ref` varchar(255) DEFAULT NULL,
  `actor_name` varchar(255) DEFAULT NULL,
  `capabilities` json NOT NULL,
  `provider_settings` json DEFAULT NULL,
  `per_run_max_usd` decimal(12,4) DEFAULT NULL,
  `daily_budget_usd` decimal(12,4) DEFAULT NULL,
  `monthly_budget_usd` decimal(12,4) DEFAULT NULL,
  `cache_ttl_seconds` int NOT NULL DEFAULT 86400,
  `qualification_version` varchar(64) DEFAULT NULL,
  `last_qualified_at` timestamp NULL DEFAULT NULL,
  `created_by` int NOT NULL,
  `updated_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_profile_ws_key` (`workspace_id`,`profile_key`),
  KEY `idx_acq_profile_ws_status` (`workspace_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_jobs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `requested_by` int NOT NULL,
  `provider_profile_id` int DEFAULT NULL,
  `consumer_type` varchar(64) NOT NULL,
  `consumer_ref` varchar(128) NOT NULL,
  `marketplace` varchar(16) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `requested_capabilities` json NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `status` enum('queued','running','review_required','confirmed','failed','canceled') NOT NULL DEFAULT 'queued',
  `priority` int NOT NULL DEFAULT 100,
  `cache_policy` enum('prefer_cache','refresh','cache_only') NOT NULL DEFAULT 'prefer_cache',
  `max_charge_usd` decimal(12,4) DEFAULT NULL,
  `cache_hit_snapshot_id` int DEFAULT NULL,
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_job_ws_idem` (`workspace_id`,`idempotency_key`),
  KEY `idx_acq_job_ws_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_acq_job_subject` (`workspace_id`,`marketplace`,`asin`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_runs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `job_id` int NOT NULL,
  `provider_profile_id` int NOT NULL,
  `attempt` int NOT NULL,
  `provider_run_id` varchar(128) DEFAULT NULL,
  `provider_request_hash` varchar(64) NOT NULL,
  `status` enum('queued','running','succeeded','partial','failed','canceled') NOT NULL DEFAULT 'queued',
  `failure_category` varchar(64) DEFAULT NULL,
  `estimated_max_usd` decimal(12,4) DEFAULT NULL,
  `charged_usd` decimal(12,4) DEFAULT NULL,
  `result_count` int DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_run_job_attempt` (`job_id`,`attempt`),
  KEY `idx_acq_run_provider_run` (`provider_profile_id`,`provider_run_id`),
  KEY `idx_acq_run_ws_status` (`workspace_id`,`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_raw_artifacts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `run_id` int NOT NULL,
  `artifact_kind` varchar(64) NOT NULL,
  `storage_key` varchar(1024) NOT NULL,
  `content_hash` varchar(64) NOT NULL,
  `content_type` varchar(128) NOT NULL,
  `size_bytes` bigint NOT NULL,
  `schema_fingerprint` varchar(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_artifact_run_hash` (`run_id`,`artifact_kind`,`content_hash`),
  KEY `idx_acq_artifact_ws_run` (`workspace_id`,`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_source_snapshots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `job_id` int NOT NULL,
  `run_id` int NOT NULL,
  `raw_artifact_id` int NOT NULL,
  `marketplace` varchar(16) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `schema_version` varchar(64) NOT NULL,
  `source_hash` varchar(64) NOT NULL,
  `normalized_data` json NOT NULL,
  `field_statuses` json NOT NULL,
  `completeness` json DEFAULT NULL,
  `status` enum('draft','pending_review','confirmed','rejected','superseded') NOT NULL DEFAULT 'draft',
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `review_note` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_snapshot_run_source` (`run_id`,`source_hash`),
  KEY `idx_acq_snapshot_subject` (`workspace_id`,`marketplace`,`asin`,`created_at`),
  KEY `idx_acq_snapshot_job` (`job_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_asset_candidates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `snapshot_id` int NOT NULL,
  `source_artifact_id` int NOT NULL,
  `role` enum('main','secondary','aplus','brand_story','video','unknown') NOT NULL DEFAULT 'unknown',
  `position_index` int NOT NULL,
  `source_json_path` varchar(512) NOT NULL,
  `source_url_hash` varchar(64) NOT NULL,
  `provider_asset_id` varchar(255) DEFAULT NULL,
  `storage_key` varchar(1024) DEFAULT NULL,
  `content_hash` varchar(64) DEFAULT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `size_bytes` bigint DEFAULT NULL,
  `width` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `module_type` varchar(64) DEFAULT NULL,
  `module_class` varchar(128) DEFAULT NULL,
  `field_status` varchar(64) NOT NULL,
  `review_status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_asset_snapshot_role_pos` (`snapshot_id`,`role`,`position_index`),
  KEY `idx_acq_asset_snapshot_status` (`snapshot_id`,`review_status`),
  KEY `idx_acq_asset_content_hash` (`workspace_id`,`content_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_snapshot_revisions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `snapshot_id` int NOT NULL,
  `version` int NOT NULL,
  `base_content_hash` varchar(64) NOT NULL,
  `patch` json NOT NULL,
  `revision_hash` varchar(64) NOT NULL,
  `reason_code` varchar(64) NOT NULL,
  `note` text,
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_revision_snapshot_ver` (`snapshot_id`,`version`),
  KEY `idx_acq_revision_ws_created` (`workspace_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_confirmed_snapshots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `snapshot_id` int NOT NULL,
  `revision_id` int DEFAULT NULL,
  `marketplace` varchar(16) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `confirmation_version` int NOT NULL,
  `content_hash` varchar(64) NOT NULL,
  `confirmed_data` json NOT NULL,
  `field_statuses` json NOT NULL,
  `confirmed_asset_ids` json NOT NULL,
  `is_current` int NOT NULL DEFAULT 1,
  `confirmed_by` int NOT NULL,
  `confirmed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_confirmed_snapshot_ver` (`snapshot_id`,`confirmation_version`),
  KEY `idx_acq_confirmed_subject` (`workspace_id`,`marketplace`,`asin`,`is_current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `acquisition_consumer_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `confirmed_snapshot_id` int NOT NULL,
  `consumer_type` varchar(64) NOT NULL,
  `consumer_ref` varchar(128) NOT NULL,
  `capability_scope` varchar(64) NOT NULL,
  `projection_version` varchar(64) NOT NULL,
  `status` enum('active','superseded','detached') NOT NULL DEFAULT 'active',
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acq_consumer_link` (`workspace_id`,`consumer_type`,`consumer_ref`,`capability_scope`,`confirmed_snapshot_id`),
  KEY `idx_acq_consumer_snapshot` (`confirmed_snapshot_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
