CREATE TABLE IF NOT EXISTS `amazon_monitor_schedules` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `monitor_kind` enum('competitor','keyword') NOT NULL,
  `monitor_id` int NOT NULL,
  `owner_user_id` int NOT NULL,
  `frequency` enum('manual','daily','weekly') NOT NULL DEFAULT 'manual',
  `cron_expression` varchar(64) DEFAULT NULL,
  `heartbeat_task_uid` varchar(128) DEFAULT NULL,
  `status` enum('draft','active','paused','error','retired') NOT NULL DEFAULT 'draft',
  `next_run_at` timestamp NULL DEFAULT NULL,
  `last_heartbeat_at` timestamp NULL DEFAULT NULL,
  `last_queued_run_id` int DEFAULT NULL,
  `last_error` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amazon_monitor_schedule_owner` (`workspace_id`,`monitor_kind`,`monitor_id`),
  UNIQUE KEY `uk_amazon_monitor_schedule_task` (`heartbeat_task_uid`),
  KEY `idx_amazon_monitor_schedule_status` (`workspace_id`,`status`,`next_run_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `amazon_monitor_runs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspace_id` int NOT NULL,
  `monitor_kind` enum('competitor','keyword') NOT NULL,
  `monitor_id` int DEFAULT NULL,
  `trigger_type` enum('manual','schedule','qualification') NOT NULL,
  `provider_profile_id` int NOT NULL,
  `requested_by` int NOT NULL,
  `marketplace` varchar(16) NOT NULL,
  `asin` varchar(20) NOT NULL,
  `keyword` varchar(500) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `depth` int DEFAULT NULL,
  `requested_capabilities` json NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `status` enum('queued','running','succeeded','partial','failed','canceled') NOT NULL DEFAULT 'queued',
  `provider_run_id` varchar(128) DEFAULT NULL,
  `provider_request_hash` varchar(64) NOT NULL,
  `estimated_max_usd` decimal(12,4) DEFAULT NULL,
  `max_charge_usd` decimal(12,4) NOT NULL,
  `charged_usd` decimal(12,4) DEFAULT NULL,
  `raw_storage_key` varchar(1024) DEFAULT NULL,
  `raw_content_hash` varchar(64) DEFAULT NULL,
  `raw_content_type` varchar(128) DEFAULT NULL,
  `raw_size_bytes` bigint DEFAULT NULL,
  `normalized_result` json DEFAULT NULL,
  `failure_category` varchar(64) DEFAULT NULL,
  `ai_job_run_id` varchar(64) DEFAULT NULL,
  `agent_run_id` varchar(64) DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_amazon_monitor_run_idem` (`workspace_id`,`idempotency_key`),
  KEY `idx_amazon_monitor_run_subject` (`workspace_id`,`monitor_kind`,`monitor_id`,`created_at`),
  KEY `idx_amazon_monitor_run_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_amazon_monitor_run_provider` (`provider_profile_id`,`provider_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
