-- Phase B listing fact and human-review governance.
-- Additive only: creates new immutable revision tables and indexes; no old table
-- is altered, no historical data is updated/backfilled, and no records are removed.

CREATE TABLE IF NOT EXISTS `listing_fact_revisions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspaceId` int NOT NULL,
  `projectId` int NOT NULL,
  `attributeKey` varchar(160) NOT NULL,
  `value` text NOT NULL,
  `valueJson` json DEFAULT NULL,
  `sourceFileId` int DEFAULT NULL,
  `proofFileId` int DEFAULT NULL,
  `proofSourceRef` varchar(512) DEFAULT NULL,
  `rawHash` varchar(64) DEFAULT NULL,
  `sourceLine` int DEFAULT NULL,
  `sourceLineHash` varchar(64) DEFAULT NULL,
  `sourceLocator` varchar(512) DEFAULT NULL,
  `provenance` enum('manual','upload','ai','legacy') NOT NULL DEFAULT 'manual',
  `status` enum('draft','confirmed','rejected','stale','legacy_unverified') NOT NULL DEFAULT 'draft',
  `revision` int NOT NULL DEFAULT 1,
  `contentHash` varchar(64) NOT NULL,
  `createdBy` int NOT NULL,
  `confirmedBy` int DEFAULT NULL,
  `confirmedAt` timestamp NULL DEFAULT NULL,
  `reviewNote` text,
  `staleAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_listing_fact_project_attribute_revision` (`projectId`,`attributeKey`,`revision`),
  KEY `idx_listing_fact_scope_status` (`workspaceId`,`projectId`,`status`,`updatedAt`),
  KEY `idx_listing_fact_source` (`workspaceId`,`projectId`,`sourceFileId`,`sourceLine`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `listing_core_revisions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `coreId` varchar(80) NOT NULL,
  `workspaceId` int NOT NULL,
  `projectId` int NOT NULL,
  `sellingPointIndex` int NOT NULL,
  `buyerReason` text NOT NULL,
  `factRevisionIdsJson` json NOT NULL,
  `keywordIdsJson` json NOT NULL,
  `status` enum('draft','confirmed','rejected','stale','superseded') NOT NULL DEFAULT 'draft',
  `revision` int NOT NULL DEFAULT 1,
  `inputHash` varchar(64) NOT NULL,
  `contentHash` varchar(64) NOT NULL,
  `createdBy` int NOT NULL,
  `confirmedBy` int DEFAULT NULL,
  `confirmedAt` timestamp NULL DEFAULT NULL,
  `staleAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_listing_core_project_core_revision` (`projectId`,`coreId`,`revision`),
  KEY `idx_listing_core_current` (`workspaceId`,`projectId`,`sellingPointIndex`,`status`,`revision`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `listing_bullet_candidates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `candidateKey` varchar(80) NOT NULL,
  `candidateRevision` int NOT NULL DEFAULT 1,
  `parentCandidateId` int DEFAULT NULL,
  `workspaceId` int NOT NULL,
  `projectId` int NOT NULL,
  `coreRevisionId` int NOT NULL,
  `jobId` int DEFAULT NULL,
  `skillRunId` int DEFAULT NULL,
  `promptVersion` varchar(64) DEFAULT NULL,
  `actualModel` varchar(128) DEFAULT NULL,
  `inputHash` varchar(64) NOT NULL,
  `subtitle` varchar(500) DEFAULT NULL,
  `fullText` text,
  `evidenceFactIdsJson` json NOT NULL,
  `gateResultJson` json NOT NULL,
  `status` enum('draft','generated','gate_failed','review_required','confirmed','rejected','stale','failed') NOT NULL DEFAULT 'draft',
  `contentHash` varchar(64) NOT NULL,
  `createdBy` int NOT NULL,
  `staleAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_listing_bullet_lineage_revision` (`coreRevisionId`,`candidateKey`,`candidateRevision`),
  KEY `idx_listing_bullet_current` (`workspaceId`,`projectId`,`coreRevisionId`,`status`,`updatedAt`),
  KEY `idx_listing_bullet_job` (`workspaceId`,`jobId`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `listing_review_revisions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspaceId` int NOT NULL,
  `projectId` int NOT NULL,
  `listingId` int DEFAULT NULL,
  `candidateId` int NOT NULL,
  `reviewRevision` int NOT NULL DEFAULT 1,
  `decision` enum('accepted','edited','rejected','revoked') NOT NULL,
  `status` enum('recorded','superseded') NOT NULL DEFAULT 'recorded',
  `beforeHash` varchar(64) DEFAULT NULL,
  `afterHash` varchar(64) DEFAULT NULL,
  `expectedRevision` int NOT NULL,
  `resultingCandidateId` int DEFAULT NULL,
  `reason` text,
  `actorId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_listing_review_candidate_revision` (`candidateId`,`reviewRevision`),
  KEY `idx_listing_review_listing_audit` (`workspaceId`,`projectId`,`listingId`,`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `listing_complete_snapshots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `workspaceId` int NOT NULL,
  `projectId` int NOT NULL,
  `listingId` int NOT NULL,
  `contentVersion` int NOT NULL,
  `fullPayloadJson` json NOT NULL,
  `fullHash` varchar(64) NOT NULL,
  `humanApprovalRef` varchar(128) DEFAULT NULL,
  `changeType` enum('generate','manual_edit','candidate_apply','optimize','translate','rollback') NOT NULL,
  `status` enum('draft','approved','stale','superseded','legacy_unverified') NOT NULL DEFAULT 'draft',
  `expectedListingVersion` int NOT NULL,
  `listingVersion` int NOT NULL,
  `createdBy` int NOT NULL,
  `approvedBy` int DEFAULT NULL,
  `approvedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_listing_complete_listing_version` (`listingId`,`contentVersion`),
  KEY `idx_listing_complete_timeline` (`workspaceId`,`projectId`,`listingId`,`createdAt`),
  KEY `idx_listing_complete_approval` (`workspaceId`,`projectId`,`status`,`approvedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
