CREATE TABLE IF NOT EXISTS `ad_dsp_reports` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `upload_id` int NOT NULL,
  `week_start_date` varchar(10),
  `week_end_date` varchar(10),
  `order_name` varchar(500),
  `order_budget` decimal(12,2) DEFAULT '0',
  `order_status` varchar(50),
  `spends` decimal(12,2) DEFAULT '0',
  `sales` decimal(12,2) DEFAULT '0',
  `orders` int DEFAULT 0,
  `impressions` int DEFAULT 0,
  `viewable_impressions` int DEFAULT 0,
  `clicks` int DEFAULT 0,
  `dpv` int DEFAULT 0,
  `total_add_to_cart` int DEFAULT 0,
  `roas` decimal(8,2) DEFAULT '0',
  `acos` decimal(8,2) DEFAULT '0',
  `ctr` decimal(8,4) DEFAULT '0',
  `line_item_type` varchar(100),
  `creative_type` varchar(100),
  `store_name` varchar(200),
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `ad_dsp_reports_id` PRIMARY KEY(`id`)
);
