-- 广告深度优化模块 - 数据基座 + 子模块数据表迁移
-- Phase 0: 五大每日报告表 + 6个子模块记录表

-- 1. 每日广告位报告表
CREATE TABLE IF NOT EXISTS `ad_daily_placement_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `upload_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT,
  `parent_asin` VARCHAR(20),
  `report_date` VARCHAR(10) NOT NULL,
  `store_name` VARCHAR(200),
  `country` VARCHAR(50),
  `ad_type` VARCHAR(10) NOT NULL,
  `portfolio_name` VARCHAR(300),
  `campaign_name` VARCHAR(500) NOT NULL,
  `placement` VARCHAR(100) NOT NULL,
  `impressions` INT DEFAULT 0,
  `clicks` INT DEFAULT 0,
  `ctr` DECIMAL(8,4),
  `cpc` DECIMAL(10,2),
  `spend` DECIMAL(12,2),
  `sales` DECIMAL(12,2),
  `direct_sales` DECIMAL(12,2),
  `indirect_sales` DECIMAL(12,2),
  `acos` DECIMAL(8,4),
  `roas` DECIMAL(8,2),
  `orders` INT DEFAULT 0,
  `direct_orders` INT DEFAULT 0,
  `indirect_orders` INT DEFAULT 0,
  `cvr` DECIMAL(8,4),
  `cpa` DECIMAL(10,2),
  `brand_new_orders` INT DEFAULT 0,
  `brand_new_sales` DECIMAL(12,2),
  `viewable_impressions` INT DEFAULT 0,
  `vtr` DECIMAL(8,4),
  `vctr` DECIMAL(8,4),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_dp_user_date` (`user_id`, `report_date`),
  INDEX `idx_dp_portfolio` (`portfolio_name`(100)),
  INDEX `idx_dp_upload` (`upload_id`)
);

-- 2. 每日搜索词报告表
CREATE TABLE IF NOT EXISTS `ad_daily_search_term_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `upload_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT,
  `parent_asin` VARCHAR(20),
  `report_date` VARCHAR(10) NOT NULL,
  `store_name` VARCHAR(200),
  `country` VARCHAR(50),
  `ad_type` VARCHAR(10) NOT NULL,
  `portfolio_name` VARCHAR(300),
  `campaign_name` VARCHAR(500),
  `ad_group_name` VARCHAR(500),
  `keyword` VARCHAR(500),
  `match_type` VARCHAR(20),
  `targeting` VARCHAR(500),
  `search_term` VARCHAR(500) NOT NULL,
  `impressions` INT DEFAULT 0,
  `clicks` INT DEFAULT 0,
  `ctr` DECIMAL(8,4),
  `cpc` DECIMAL(10,2),
  `spend` DECIMAL(12,2),
  `sales` DECIMAL(12,2),
  `direct_sales` DECIMAL(12,2),
  `indirect_sales` DECIMAL(12,2),
  `acos` DECIMAL(8,4),
  `roas` DECIMAL(8,2),
  `orders` INT DEFAULT 0,
  `direct_orders` INT DEFAULT 0,
  `indirect_orders` INT DEFAULT 0,
  `cvr` DECIMAL(8,4),
  `cpa` DECIMAL(10,2),
  `avg_order_value` DECIMAL(10,2),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_dst_user_date` (`user_id`, `report_date`),
  INDEX `idx_dst_portfolio` (`portfolio_name`(100)),
  INDEX `idx_dst_search_term` (`search_term`(100)),
  INDEX `idx_dst_upload` (`upload_id`)
);

-- 3. 每日搜索词展示量份额报告表
CREATE TABLE IF NOT EXISTS `ad_daily_impression_share_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `upload_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT,
  `parent_asin` VARCHAR(20),
  `report_date` VARCHAR(10) NOT NULL,
  `store_name` VARCHAR(200),
  `country` VARCHAR(50),
  `ad_type` VARCHAR(10) DEFAULT 'SP',
  `portfolio_name` VARCHAR(300),
  `campaign_name` VARCHAR(500),
  `ad_group_name` VARCHAR(500),
  `targeting` VARCHAR(500),
  `search_term` VARCHAR(500),
  `impression_share` DECIMAL(8,4),
  `impression_rank` INT,
  `impressions` INT DEFAULT 0,
  `clicks` INT DEFAULT 0,
  `ctr` DECIMAL(8,4),
  `spend` DECIMAL(12,2),
  `sales` DECIMAL(12,2),
  `acos` DECIMAL(8,4),
  `orders` INT DEFAULT 0,
  `top_competitor_share` DECIMAL(8,4),
  `top_competitor_asin` VARCHAR(20),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_dis_user_date` (`user_id`, `report_date`),
  INDEX `idx_dis_portfolio` (`portfolio_name`(100)),
  INDEX `idx_dis_upload` (`upload_id`)
);

-- 4. 每日SB Benchmark广告报告表
CREATE TABLE IF NOT EXISTS `ad_daily_sb_benchmark_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `upload_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT,
  `parent_asin` VARCHAR(20),
  `report_date` VARCHAR(10) NOT NULL,
  `store_name` VARCHAR(200),
  `country` VARCHAR(50),
  `campaign_name` VARCHAR(500) NOT NULL,
  `ad_format` VARCHAR(50),
  `impressions` INT DEFAULT 0,
  `clicks` INT DEFAULT 0,
  `ctr` DECIMAL(8,4),
  `cpc` DECIMAL(10,2),
  `spend` DECIMAL(12,2),
  `sales` DECIMAL(12,2),
  `acos` DECIMAL(8,4),
  `roas` DECIMAL(8,2),
  `orders` INT DEFAULT 0,
  `dpv` INT DEFAULT 0,
  `new_to_brand_orders` INT DEFAULT 0,
  `new_to_brand_sales` DECIMAL(12,2),
  `new_to_brand_rate` DECIMAL(8,4),
  `benchmark_ctr` DECIMAL(8,4),
  `benchmark_cpc` DECIMAL(10,2),
  `benchmark_acos` DECIMAL(8,4),
  `benchmark_roas` DECIMAL(8,2),
  `benchmark_cvr` DECIMAL(8,4),
  `benchmark_dpv_rate` DECIMAL(8,4),
  `benchmark_new_to_brand_rate` DECIMAL(8,4),
  `ctr_vs_benchmark` VARCHAR(20),
  `cpc_vs_benchmark` VARCHAR(20),
  `acos_vs_benchmark` VARCHAR(20),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_dsb_user_date` (`user_id`, `report_date`),
  INDEX `idx_dsb_upload` (`upload_id`)
);

-- 5. 每日业务报告表
CREATE TABLE IF NOT EXISTS `ad_daily_business_reports` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `upload_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT,
  `parent_asin` VARCHAR(20),
  `child_asin` VARCHAR(20),
  `report_date` VARCHAR(10) NOT NULL,
  `store_name` VARCHAR(200),
  `country` VARCHAR(50),
  `sku` VARCHAR(100),
  `product_name` VARCHAR(500),
  `sessions` INT DEFAULT 0,
  `session_percentage` DECIMAL(8,4),
  `page_views` INT DEFAULT 0,
  `page_views_percentage` DECIMAL(8,4),
  `buy_box_percentage` DECIMAL(8,4),
  `units_ordered` INT DEFAULT 0,
  `units_ordered_b2b` INT DEFAULT 0,
  `unit_session_percentage` DECIMAL(8,4),
  `unit_session_percentage_b2b` DECIMAL(8,4),
  `ordered_product_sales` DECIMAL(12,2),
  `ordered_product_sales_b2b` DECIMAL(12,2),
  `total_order_items` INT DEFAULT 0,
  `total_order_items_b2b` INT DEFAULT 0,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_dbr_user_date` (`user_id`, `report_date`),
  INDEX `idx_dbr_asin` (`child_asin`),
  INDEX `idx_dbr_upload` (`upload_id`)
);

-- 6. 产品周期判定记录表 (子模块1)
CREATE TABLE IF NOT EXISTS `ad_product_stages` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `portfolio_names` TEXT,
  `parent_asin` VARCHAR(20),
  `date_range_start` VARCHAR(10) NOT NULL,
  `date_range_end` VARCHAR(10) NOT NULL,
  `stage` VARCHAR(20) NOT NULL,
  `confidence` INT DEFAULT 0,
  `evidence` TEXT,
  `red_flags` TEXT,
  `daily_highlights` TEXT,
  `strategy` TEXT,
  `transition_signals` TEXT,
  `user_edits` TEXT,
  `status` ENUM('draft','confirmed','archived') DEFAULT 'draft' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_ps_user` (`user_id`),
  INDEX `idx_ps_status` (`status`)
);

-- 7. 关键词分级记录表 (子模块2)
CREATE TABLE IF NOT EXISTS `ad_keyword_tiers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `portfolio_names` TEXT,
  `date_range_start` VARCHAR(10) NOT NULL,
  `date_range_end` VARCHAR(10) NOT NULL,
  `keyword` VARCHAR(500) NOT NULL,
  `tier` VARCHAR(20) NOT NULL,
  `role` VARCHAR(20),
  `current_performance` VARCHAR(20),
  `daily_trend` VARCHAR(20),
  `anomaly_dates` TEXT,
  `action` TEXT,
  `bid_suggestion` TEXT,
  `priority` VARCHAR(10),
  `reason` TEXT,
  `user_edited` INT DEFAULT 0,
  `user_action` TEXT,
  `status` ENUM('pending','confirmed','ignored') DEFAULT 'pending' NOT NULL,
  `batch_id` INT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_kt_user` (`user_id`),
  INDEX `idx_kt_batch` (`batch_id`),
  INDEX `idx_kt_keyword` (`keyword`(100))
);

-- 8. 串联诊断记录表 (子模块3)
CREATE TABLE IF NOT EXISTS `ad_diagnoses` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `portfolio_names` TEXT,
  `date_range_start` VARCHAR(10) NOT NULL,
  `date_range_end` VARCHAR(10) NOT NULL,
  `diagnosis_result` TEXT,
  `overall_verdict` TEXT,
  `priority_actions` TEXT,
  `warning` TEXT,
  `user_edits` TEXT,
  `status` ENUM('draft','confirmed','archived') DEFAULT 'draft' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_diag_user` (`user_id`)
);

-- 9. 五大报表独立分析记录表 (子模块4)
CREATE TABLE IF NOT EXISTS `ad_report_analysis_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `report_type` VARCHAR(30) NOT NULL,
  `portfolio_names` TEXT,
  `date_range_start` VARCHAR(10) NOT NULL,
  `date_range_end` VARCHAR(10) NOT NULL,
  `analysis_result` TEXT,
  `action_items` TEXT,
  `user_edits` TEXT,
  `status` ENUM('draft','confirmed','archived') DEFAULT 'draft' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_rar_user` (`user_id`),
  INDEX `idx_rar_type` (`report_type`)
);

-- 10. SOP任务清单表 (子模块5)
CREATE TABLE IF NOT EXISTS `ad_sop_tasks` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `portfolio_names` TEXT,
  `period` VARCHAR(20) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT,
  `evidence` TEXT,
  `priority` VARCHAR(10),
  `status` ENUM('pending','in_progress','completed','skipped') DEFAULT 'pending' NOT NULL,
  `completedAt` TIMESTAMP NULL,
  `completed_note` TEXT,
  `source_module` VARCHAR(30),
  `source_record_id` INT,
  `due_date` VARCHAR(10),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_sop_user` (`user_id`),
  INDEX `idx_sop_status` (`status`),
  INDEX `idx_sop_period` (`period`)
);

-- 11. 疑难杂症AI诊所记录表 (子模块6)
CREATE TABLE IF NOT EXISTS `ad_clinic_records` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `portfolio_names` TEXT,
  `date_range_start` VARCHAR(10),
  `date_range_end` VARCHAR(10),
  `symptom_category` VARCHAR(50),
  `symptom_description` TEXT,
  `additional_context` TEXT,
  `diagnosis` TEXT,
  `prescription` TEXT,
  `user_edits` TEXT,
  `status` ENUM('consulting','diagnosed','treating','resolved','archived') DEFAULT 'consulting' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `idx_clinic_user` (`user_id`),
  INDEX `idx_clinic_status` (`status`)
);

-- 12. 扩展 ad_report_uploads 的 report_type 枚举（添加每日报告类型）
ALTER TABLE `ad_report_uploads` MODIFY COLUMN `report_type` ENUM(
  'search_term',
  'campaign',
  'placement',
  'hourly',
  'order',
  'dsp',
  'daily_placement',
  'daily_search_term',
  'daily_impression_share',
  'daily_sb_benchmark',
  'daily_business'
) NOT NULL;
