export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  authMode: (process.env.AUTH_MODE ?? "manus").trim().toLowerCase(),
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmProvider: (process.env.LLM_PROVIDER ?? "forge").trim().toLowerCase(),
  externalLlmBaseUrl: process.env.EXTERNAL_LLM_BASE_URL ?? "",
  externalLlmApiKey: process.env.EXTERNAL_LLM_API_KEY ?? "",
  externalLlmModel: process.env.EXTERNAL_LLM_MODEL ?? "",
  storageProvider: (process.env.STORAGE_PROVIDER ?? "forge").trim().toLowerCase(),
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3ForcePathStyle: process.env.S3_FORCE_PATH_STYLE === "true",
  storagePresignExpiresSeconds: Number(process.env.STORAGE_PRESIGN_EXPIRES_SECONDS ?? "3600"),
  // Deployment configuration
  companyName: process.env.COMPANY_NAME ?? "跨海\uD83D\uDC4D",
  companyLogo: process.env.COMPANY_LOGO ?? "",
  erpType: process.env.ERP_TYPE ?? "excel", // Changed from "lingxing" - data now imported via Excel
  instanceId: process.env.INSTANCE_ID ?? "instance-a",
  // Peer sync configuration
  peerSyncEnabled: process.env.PEER_SYNC_ENABLED === "true",
  peerApiUrl: process.env.PEER_API_URL ?? "",
  peerApiKey: process.env.PEER_API_KEY ?? "",
  // Usage reporting
  usageReportEnabled: process.env.USAGE_REPORT_ENABLED === "true",
  usageReportUrl: process.env.USAGE_REPORT_URL ?? "",
};
