import {
  BookOpenCheck,
  Clapperboard,
  ClipboardList,
  Database,
  Eye,
  FileCheck2,
  FileText,
  Film,
  Image,
  Key,
  Layers,
  Layout,
  LayoutGrid,
  Lightbulb,
  Palette,
  PenLine,
  Search,
  Scissors,
  Sparkles,
  Target,
  Upload,
  Video,
} from "lucide-react";
import type { WorkflowStepDefinition } from "./types";

export const LISTING_AGENT_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  {
    id: 1,
    label: "产品基本信息录入",
    shortLabel: "基本信息",
    icon: ClipboardList,
    description: "录入产品名称、ASIN、类目、目标市场等资料",
    agentNodeId: "N0",
    artifactKey: "project_profile",
  },
  {
    id: 2,
    label: "竞品Listing分析及图片分析",
    shortLabel: "竞品分析",
    icon: Search,
    description: "分析竞品 Listing 与图片表达，提炼差异方向",
    agentNodeId: "N1",
    artifactKey: "competitor_analysis",
  },
  {
    id: 3,
    label: "卖点梳理",
    shortLabel: "卖点梳理",
    icon: Lightbulb,
    description: "梳理核心卖点、差异化优势与证据链",
    agentNodeId: "G1",
    artifactKey: "selling_points",
  },
  {
    id: 4,
    label: "埋词词库",
    shortLabel: "埋词词库",
    icon: Key,
    description: "整理核心词、长尾词、场景词与埋词策略",
    agentNodeId: "G4",
    artifactKey: "search_terms",
  },
  {
    id: 5,
    label: "图片和文案大纲",
    shortLabel: "图文大纲",
    icon: Image,
    description: "规划图片结构、文案框架与 A+ 模块方向",
    agentNodeId: "E1",
    artifactKey: "image_outline",
  },
  {
    id: 6,
    label: "风格参考及确认",
    shortLabel: "风格确认",
    icon: Palette,
    description: "确认视觉风格、色调、排版与参考方向",
    agentNodeId: "E1_STYLE",
    artifactKey: "style_reference",
  },
  {
    id: 7,
    label: "套图文档",
    shortLabel: "套图文档",
    icon: LayoutGrid,
    description: "输出每张图的尺寸、内容、文字与设计说明",
    agentNodeId: "E1_DOC",
    artifactKey: "image_document",
  },
  {
    id: 8,
    label: "Listing定稿",
    shortLabel: "Listing定稿",
    icon: FileText,
    description: "确认 Title、Bullet、Description、Search Terms",
    agentNodeId: "O1",
    artifactKey: "listing_final",
  },
  {
    id: 9,
    label: "爆款视频拆解",
    shortLabel: "视频拆解",
    icon: Video,
    description: "拆解同类视频结构、节奏与卖点呈现",
    agentNodeId: "E2",
    artifactKey: "video_breakdown",
  },
  {
    id: 10,
    label: "视频剪辑脚本",
    shortLabel: "视频脚本",
    icon: Clapperboard,
    description: "输出分镜、旁白、字幕、时长等脚本内容",
    agentNodeId: "E2_SCRIPT",
    artifactKey: "video_script",
  },
];

export const IMAGE_SUGGESTION_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: 0, label: "竞品分析", icon: Search, description: "竞品图片上传与分析", agentNodeId: "image.step0", artifactKey: "competitor_image_analysis" },
  { id: 1, label: "卖点梳理", icon: Target, description: "AI 分析与人工确认", agentNodeId: "image.step1", artifactKey: "selling_points" },
  { id: 2, label: "图片大纲", icon: Layout, description: "图片内容规划与确认", agentNodeId: "image.step2", artifactKey: "image_outline" },
  { id: 3, label: "风格确认", icon: Palette, description: "视觉风格选择", agentNodeId: "image.step3", artifactKey: "style_reference" },
  { id: 4, label: "参考图确认", icon: Eye, description: "构图与效果参考", agentNodeId: "image.step4", artifactKey: "reference_images" },
  { id: 5, label: "图片建议", icon: FileCheck2, description: "最终输出与锁定", agentNodeId: "image.step5", artifactKey: "final_image_advice" },
];

export const AD_STRUCTURE_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: "data", label: "数据准备", icon: Database, description: "项目、关键词、竞品数据" },
  { id: "generate", label: "AI生成", icon: Sparkles, description: "生成广告架构" },
  { id: "review", label: "人工确认", icon: BookOpenCheck, description: "检查投放矩阵与预算" },
  { id: "edit", label: "编辑版本", icon: PenLine, description: "调整关键词、竞价、预算" },
  { id: "export", label: "输出归档", icon: Upload, description: "CSV / Bulk Sheet" },
];

export const VIDEO_SCRIPT_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: "stage_0a", label: "竞品脚本分析", icon: Eye, description: "上传或提取竞品视频脚本", agentNodeId: "video.stage_0a", artifactKey: "competitor_script" },
  { id: "stage_0b", label: "产品信息提取", icon: Database, description: "从项目提取产品数据", agentNodeId: "video.stage_0b", artifactKey: "product_context" },
  { id: "stage_1", label: "段落规划", icon: FileText, description: "规划视频段落结构", agentNodeId: "video.stage_1", artifactKey: "section_plan" },
  { id: "stage_2", label: "子主题展开", icon: Layers, description: "展开子主题与镜头数量", agentNodeId: "video.stage_2", artifactKey: "subtopics" },
  { id: "stage_3", label: "镜头明细", icon: Film, description: "逐镜头拍摄脚本", agentNodeId: "video.stage_3", artifactKey: "shot_list" },
  { id: "stage_4", label: "剪辑脚本", icon: Scissors, description: "多版本剪辑方案", agentNodeId: "video.stage_4", artifactKey: "edit_script" },
];

export const WORKFLOW_FRAMEWORK_MODULES = {
  listing: LISTING_AGENT_WORKFLOW_STEPS,
  image: IMAGE_SUGGESTION_WORKFLOW_STEPS,
  ads: AD_STRUCTURE_WORKFLOW_STEPS,
  video: VIDEO_SCRIPT_WORKFLOW_STEPS,
} as const;
