import {
  BookOpenCheck,
  Clapperboard,
  ClipboardList,
  Database,
  Eye,
  FileCheck2,
  FileText,
  Film,
  Gauge,
  GitCompareArrows,
  HelpCircle,
  Image,
  Key,
  Layers,
  Layout,
  LayoutGrid,
  Lightbulb,
  MessageSquareText,
  Palette,
  PenLine,
  Search,
  Scissors,
  Sparkles,
  Target,
  Upload,
  Video,
} from "lucide-react";
import type { WorkflowStepDefinition } from "./types";

export const LISTING_AGENT_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  {
    id: "N0",
    label: "N0 · 项目管理",
    shortLabel: "N0",
    icon: ClipboardList,
    description: "品牌、产品、类目、市场基础信息",
    agentNodeId: "N0",
    artifactKey: "project",
  },
  {
    id: "N1",
    label: "N1 · 竞品分析",
    shortLabel: "N1",
    icon: Search,
    description: "ASIN 分析与竞品 Listing 文本",
    agentNodeId: "N1",
    artifactKey: "competitorAnalysis",
  },
  {
    id: "N2",
    label: "N2 · 竞品对比",
    shortLabel: "N2",
    icon: GitCompareArrows,
    description: "多竞品横向对比",
    agentNodeId: "N2",
    artifactKey: "competitorComparison",
  },
  {
    id: "N3",
    label: "N3 · 数据文件",
    shortLabel: "N3",
    icon: Database,
    description: "产品属性、Rufus、买家问题",
    agentNodeId: "N3",
    artifactKey: "productAttributes",
  },
  {
    id: "N4",
    label: "N4 · 关键词管理",
    shortLabel: "N4",
    icon: Key,
    description: "关键词矩阵与词根分类",
    agentNodeId: "N4",
    artifactKey: "keywordMatrix",
  },
  {
    id: "N5",
    label: "N5 · 评论聚合分析",
    shortLabel: "N5",
    icon: MessageSquareText,
    description: "痛点、痒点、爽点提取",
    agentNodeId: "N5",
    artifactKey: "reviewAggregation",
  },
  {
    id: "G1",
    label: "G1 · 卖点精雕",
    shortLabel: "G1",
    icon: Sparkles,
    description: "7条卖点核心方向",
    agentNodeId: "G1",
    artifactKey: "sellingPoints",
  },
  {
    id: "G2",
    label: "G2 · 标题生成",
    shortLabel: "G2",
    icon: FileText,
    description: "200字符内核心词前置",
    agentNodeId: "G2",
    artifactKey: "title",
  },
  {
    id: "G3",
    label: "G3 · 产品描述",
    shortLabel: "G3",
    icon: FileText,
    description: "长描述与A+内容规划",
    agentNodeId: "G3",
    artifactKey: "description",
  },
  {
    id: "G4",
    label: "G4 · 搜索词",
    shortLabel: "G4",
    icon: Key,
    description: "后台关键词 250 字符",
    agentNodeId: "G4",
    artifactKey: "searchTerms",
  },
  {
    id: "G5",
    label: "G5 · QA问答",
    shortLabel: "G5",
    icon: HelpCircle,
    description: "买家问题与专业解答",
    agentNodeId: "G5",
    artifactKey: "qaContent",
  },
  {
    id: "O1",
    label: "O1 · 结果预览",
    shortLabel: "O1",
    icon: FileText,
    description: "完整Listing中英文版本",
    agentNodeId: "O1",
    artifactKey: "listingPreview",
  },
  {
    id: "O2",
    label: "O2 · Listing评分",
    shortLabel: "O2",
    icon: Gauge,
    description: "多维度质量评估",
    agentNodeId: "O2",
    artifactKey: "listingScore",
  },
  {
    id: "O3",
    label: "O3 · 广告架构",
    shortLabel: "O3",
    icon: Target,
    description: "广告词与投放策略",
    agentNodeId: "O3",
    artifactKey: "adStructure",
  },
  {
    id: "E1",
    label: "E1 · 智能图片建议",
    shortLabel: "E1",
    icon: Image,
    description: "图片结构与构图建议",
    agentNodeId: "E1",
    artifactKey: "imageAdvice",
  },
  {
    id: "E2",
    label: "E2 · 视频脚本",
    shortLabel: "E2",
    icon: Video,
    description: "产品视频脚本与分镜",
    agentNodeId: "E2",
    artifactKey: "videoScript",
  },
];

export const IMAGE_SUGGESTION_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: 0, label: "竞品分析", icon: Search, description: "竞品图片上传与分析", agentNodeId: "image.step0", artifactKey: "competitor_image_analysis" },
  { id: 1, label: "卖点梳理", icon: Target, description: "AI 分析与人工确认", agentNodeId: "image.step1", artifactKey: "selling_points" },
  { id: 2, label: "图片大纲", icon: Layout, description: "图片内容规划与确认", agentNodeId: "image.step2", artifactKey: "image_outline" },
  { id: 3, label: "风格确认", icon: Palette, description: "视觉风格选择", agentNodeId: "image.step3", artifactKey: "style_reference" },
  { id: 4, label: "参考图确认", icon: Eye, description: "构图与效果参考", agentNodeId: "image.step4", artifactKey: "reference_images" },
  { id: 5, label: "图片建议", icon: FileCheck2, description: "最终输出与锁定", agentNodeId: "image.step5", artifactKey: "final_image_advice" },
];

export const AD_STRUCTURE_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: "data", label: "数据准备", icon: Database, description: "项目、关键词、竞品数据" },
  { id: "generate", label: "AI生成", icon: Sparkles, description: "生成广告架构" },
  { id: "review", label: "人工确认", icon: BookOpenCheck, description: "检查投放矩阵与预算" },
  { id: "edit", label: "编辑版本", icon: PenLine, description: "调整关键词、竞价、预算" },
  { id: "export", label: "输出归档", icon: Upload, description: "CSV / Bulk Sheet" },
];

export const VIDEO_SCRIPT_WORKFLOW_STEPS: WorkflowStepDefinition[] = [
  { id: "stage_0a", label: "竞品脚本分析", icon: Eye, description: "上传或提取竞品视频脚本", agentNodeId: "video.stage_0a", artifactKey: "competitor_script" },
  { id: "stage_0b", label: "产品信息提取", icon: Database, description: "从项目提取产品数据", agentNodeId: "video.stage_0b", artifactKey: "product_context" },
  { id: "stage_1", label: "段落规划", icon: FileText, description: "规划视频段落结构", agentNodeId: "video.stage_1", artifactKey: "section_plan" },
  { id: "stage_2", label: "子主题展开", icon: Layers, description: "展开子主题与镜头数量", agentNodeId: "video.stage_2", artifactKey: "subtopics" },
  { id: "stage_3", label: "镜头明细", icon: Film, description: "逐镜头拍摄脚本", agentNodeId: "video.stage_3", artifactKey: "shot_list" },
  { id: "stage_4", label: "剪辑脚本", icon: Scissors, description: "多版本剪辑方案", agentNodeId: "video.stage_4", artifactKey: "edit_script" },
];

export const WORKFLOW_FRAMEWORK_MODULES = {
  listing: LISTING_AGENT_WORKFLOW_STEPS,
  image: IMAGE_SUGGESTION_WORKFLOW_STEPS,
  ads: AD_STRUCTURE_WORKFLOW_STEPS,
  video: VIDEO_SCRIPT_WORKFLOW_STEPS,
} as const;
